a = int("1")
b = int("1200")
c = float("0.5")
d = str(190000)
e = str(0.123)
f = bool("0")
g = bool(0)

print(f"a: {a}, {type(a)}")
print(f"b: {b}, {type(b)}")
print(f"c: {c}, {type(c)}")
print(f"d: {d}, {type(d)}")
print(f"e: {e}, {type(e)}")
print(f"f: {f}, {type(f)}")
print(f"g: {g}, {type(g)}")