a = 10
print(f"a = {a} {type(a)}")
a += 5
print(f"a = {a} {type(a)}")
a -= 5
print(f"a = {a} {type(a)}")
a *= 5
print(f"a = {a} {type(a)}")
a /= 5
print(f"a = {a} {type(a)}")
a **= 3
print(f"a = {a} {type(a)}")
a //= 5
print(f"a = {a} {type(a)}")
a %= 3
print(f"a = {a} {type(a)}")
